version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    time: "02:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: rspec-rails
    versions:
    - 4.0.2
    - 4.1.0
    - 5.0.0
  - dependency-name: sdoc
    versions:
    - 2.0.3
    - 2.0.4
  - dependency-name: rails
    versions:
    - 5.2.4.5
  - dependency-name: database_cleaner
    versions:
    - 2.0.0
  - dependency-name: newrelic_rpm
    versions:
    - 6.15.0
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "02:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: grunt-cli
    versions:
    - 1.4.1
  - dependency-name: karma
    versions:
    - 6.1.1
    - 6.1.2
    - 6.2.0
    - 6.3.0
    - 6.3.1
  - dependency-name: jasmine-core
    versions:
    - 3.7.0
